baseURL: http://example.org/
languageCode: es-es
title: My Blog en Hugo
theme: smigle



markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - identifier: home
      name: Inicio
      url: /.
      weight: 1
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: categories
      name: Categorías
      url: /categories/
      weight: 20
    - identifier: tags
      name: Etiquetas
      url: /tags/
      weight: 30
    - identifier: about
      name: Sobre mí
      url: /about/
      weight: 40
  
  
params:
  subtitle: ¡El subtítulo va aquí!
  dateFmt: 02.01.2006
  social:
      - name: GitHub
        url: https://github.com/ian-s-mcb
      - name: GitLab
        url: https://gitlab.com/ian-s-mcb
      - name: Quizlet
        url: https://quizlet.com/ian-s-mcb
      - name: Reddit
        url: https://www.reddit.com/user/ian-s-mcb
      - name: StackOverflow
        url: https://stackoverflow.com/users/3417846/ian-s-mcb
